name: dio_cache_interceptor_file_store
description: A filesystem cache store implementation for dio_cache_interceptor package.
homepage: https://github.com/llfbandit/dio_cache_interceptor/tree/master/dio_cache_interceptor_file_store
version: 1.1.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio_cache_interceptor:
    git:
      url: git://github.com/krapk/dio_cache_interceptor.git
      path: dio_cache_interceptor

  # https://pub.dev/packages/path
  path: ^1.8.0
  # https://pub.dev/packages/synchronized
  synchronized: ^3.0.0

dev_dependencies:
  # https://pub.dev/packages/lints
  lints: ^1.0.1
  # https://pub.dev/packages/test
  test: ^1.18.0
